# Generated by Django 5.2 on 2025-04-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_adm', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=70)),
                ('finca', models.CharField(max_length=8)),
                ('contraseña', models.CharField(max_length=8)),
                ('confcontraseña', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_per', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=50)),
                ('cor_per', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=15)),
                ('foto', models.TextField()),
            ],
            options={
                'db_table': 'agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_ani', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('raza', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalCompraventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'animal_compraventa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompraVenta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_comven', models.CharField(db_column='Tipo_ComVen', max_length=45)),
                ('fecha', models.DateField()),
                ('precio_total', models.FloatField()),
                ('peso_anicomven', models.FloatField(db_column='peso_aniComVen')),
                ('lugar', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'compra_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetCompraventa',
            fields=[
                ('cod_det', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('pre_uni', models.FloatField()),
            ],
            options={
                'db_table': 'det_compraventa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('num_doc', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('tip_doc', models.CharField(max_length=45)),
                ('fecha_doc', models.DateField()),
            ],
            options={
                'db_table': 'documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('cod_eve', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=70)),
                ('fecha_eve', models.DateField()),
                ('hora_eve', models.TimeField()),
                ('estado', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'evento',
                'managed': False,
            },
        ),
    ]
