# Generated by Django 5.2 on 2025-04-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo2', '0002_administrador_agenda_animal_compraventa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('administrador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mundo2.administrador')),
                ('modulo_inventario', models.BooleanField(default=True)),
                ('modulo_ventas', models.BooleanField(default=True)),
                ('modulo_calendario', models.BooleanField(default=True)),
                ('modulo_documentos', models.BooleanField(default=True)),
                ('modulo_agenda', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'perfil_usuario',
                'managed': False,
            },
        ),
    ]
