# Generated by Django 5.2 on 2025-04-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo2', '0003_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('cod_com', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_prov', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('precio_total', models.FloatField()),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_cont', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=245)),
                ('nombre', models.CharField(max_length=250)),
                ('correo', models.CharField(max_length=270)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetCom',
            fields=[
                ('cod_detcom', models.AutoField(primary_key=True, serialize=False)),
                ('peso_anicom', models.FloatField(db_column='peso_aniCom')),
                ('precio_uni', models.FloatField()),
            ],
            options={
                'db_table': 'det_com',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetVen',
            fields=[
                ('cod_detven', models.AutoField(primary_key=True, serialize=False)),
                ('peso_aniven', models.FloatField(db_column='peso_aniVen')),
                ('precio_uni', models.FloatField()),
            ],
            options={
                'db_table': 'det_ven',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('cod_ven', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_cli', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=50)),
                ('precio_total', models.FloatField()),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CompraVenta',
        ),
        migrations.DeleteModel(
            name='DetCompraventa',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
