# Generated by Django 5.2 on 2025-04-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundo2', '0002_administrador_agenda_animal_animalcompraventa_and_more'),
        ('mundo2', '0004_compra_contacto_detcom_detven_venta_and_more'),
    ]

    operations = [
    ]
