# Generated by Django 5.2 on 2025-04-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundo2', '0005_merge_20250424_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimalCompraventa',
        ),
        migrations.DeleteModel(
            name='CompraVenta',
        ),
        migrations.DeleteModel(
            name='DetCompraventa',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
